name: Update data and publish report

on:
#  schedule:
#    - cron: '0 0 1 * *'  # Exécuter le 1er de chaque mois à minuit
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: aqlt/publishtc:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify Git directory
      run: |
        if [ ! -d ".git" ]; then
          echo ".git directory not found!"
          exit 1
        fi

    - name: List of files
      run: ls -la

    - name: restore
      run: R -e "renv::restore()"

    - name: Update data
      run: Rscript R/1-download-data.R

    - name: Update Trend-Cycle estimates
      run: Rscript R/2-compute-tc.R

    - name: Commit changes
      run: |
        git config --global user.name actions-user
        git config --global user.email "actions@github.com"
        git add data
        git commit -m "Update data"
        git push
      env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions

    - name: Render documents
      run: Rscript R/3-render.R

    - name: Deploy to gh-pages
      run: |
        git checkout --orphan latest_branch
        # Supprimer tous les fichiers sauf le dossier .git
        shopt -s extglob
        rm -rf !(report|.git)
        #find . -maxdepth 1 ! -name '.git' ! -name 'report' -exec rm -rf {} +
        git reset
        # Copier uniquement les fichiers HTML du dossier report à la racine
        cp report/*.html .
        [ -f template.html ] && rm template.html
        git add *.html
        git commit -m "Update reports"
        git branch -D gh-pages
        git branch -m gh-pages
        git push origin gh-pages --force
      env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions

